trigger:
- main

variables:
- group: variable

pool:
  vmImage: ubuntu-latest


steps:
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gcr'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: 'src/Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'

- task: DownloadSecureFile@1
  name: serviceAccount
  inputs:
    secureFile: 'service.json'
- task: GoogleCloudSdkInstaller@0
  inputs:
    version: '306.0.0'

- task: GcloudRunner@0
  inputs:
    command: 'auth activate-service-account'
    arguments: '--key-file $(serviceAccount.secureFilePath)'
  displayName: 'gcloud auth activate-service-account'

- task: GcloudRunner@0
  inputs:
    command: 'run deploy clouddemo'
    arguments: |
      --service-account=clouddemo-runner@$(CloudRun.ProjectId.Development).iam.gserviceaccount.com --allow-unauthenticated --image=gcr.io/$(ContainerRegistry.ProjectId)/clouddemo:$BUILD_BUILDID --platform=managed --region=$(CloudRun.Region) --project=$(CloudRun.ProjectId.Development)
    quiet: true
  displayName: 'Deploy'
