repos:
    - repo: https://github.com/psf/black
      rev: 21.5b1
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: check-added-large-files
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-docstring-first
        - id: detect-private-key
        - id: requirements-txt-fixer
        - id: no-commit-to-branch
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
      language_version: python3.6
    - repo: https://gitlab.com/PyCQA/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
        args: [--max-line-length=131]
    - repo: https://github.com/pycqa/isort
      rev: 5.9.3
      hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
