repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        - id: check-added-large-files
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-docstring-first
        - id: detect-private-key
        - id: requirements-txt-fixer
        - id: no-commit-to-branch
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
      - id: black
      language_version: python3.6
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
      - id: flake8
        args: [--max-line-length=131, --extend-ignore=E203]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
