parameters:
- name: env
  type: string
  default: 'dev'
- name: build_id
  type: string
  default: 'latest'
- name: project_id
  type: string
- name: serviceAccounts
  type: string

jobs:
- deployment: CD_${{ parameters.env }}
  displayName: CD for ${{ parameters.env }}
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            gcloud auth activate-service-account --quiet --key-file <(echo ${{ parameters.serviceAccounts }} | base64 -d)
          displayName: 'Authorize gcp'

        - script: |
            gcloud run deploy run-kitsune-${{ parameters.env }}-asia-northeast1 \
            --quiet \
            --service-account=cloud-runner@${{ parameters.project_id }}.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --image=gcr.io/kitsune-321314/kitsune-backend:${{ parameters.build_id }} \
            --platform=managed \
            --region=asia-northeast1 \
            --project=${{ parameters.project_id }}
          displayName: 'Cloud Run'
